### ISSUE TITLE
An error during terraform apply

### ISSUE THREAD

**Issue by mkosynskyi** [terraform-aws-modules/terraform-aws-redshift#10]
```hcl
provider "aws" {
  region = "eu-west-1"
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
}

######
# VPC
######
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "demo-vpc"

  cidr = "10.10.0.0/16"

  azs              = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  redshift_subnets = ["10.10.41.0/24", "10.10.42.0/24", "10.10.43.0/24"]
}

###########################
# Security group
###########################
module "sg" {
  source = "terraform-aws-modules/security-group/aws//modules/redshift"

  name   = "demo-redshift"
  vpc_id = "${module.vpc.vpc_id}"

  # Allow ingress rules to be accessed only within current VPC
  ingress_cidr_blocks = ["${module.vpc.vpc_cidr_block}"]

  # Allow all rules for all protocols
  egress_rules = ["all-all"]
}

###########
# Redshift
###########
module "redshift" {
  source  = "terraform-aws-modules/redshift/aws"
  version = "1.4.0"

  cluster_identifier      = "my-cluster"
  cluster_node_type       = "dc1.large"
  cluster_number_of_nodes = 1

  cluster_database_name   = "mydb"
  cluster_master_username = "mydbuser"
  cluster_master_password = "MySecretPassw0rd"

  subnets                = ["${module.vpc.redshift_subnets}"]
  vpc_security_group_ids = ["${module.sg.this_security_group_id}"]

}
```

Error: Error applying plan:

1 error(s) occurred:

* module.redshift.aws_redshift_subnet_group.this: 1 error(s) occurred:

* aws_redshift_subnet_group.this: Error creating Redshift Subnet Group: ClusterSubnetGroupAlreadyExists: The Cluster subnet group 'my-cluster' already exists.
	status code: 400, request id: 061d64b6-d2f5-11e8-817d-3be39d2ae2d8

**Comment by antonbabenko** [comment]
Hi @mkosynskyi !

The problem you are experiencing happens because both `terraform-aws-modules/vpc/aws` and `terraform-aws-modules/redshift/aws` modules are trying to create the same resource type `aws_redshift_subnet_group`.

It is not possible to disable creation of `aws_redshift_subnet_group` inside VPC module when you specify `redshift_subnets`, but you can add an argument to `redshift` module like this to use the one which was created inside VPC module:

```hcl
module "redshift" {
  # ... the same as you have already

  redshift_subnet_group_name = "${module.vpc.redshift_subnet_group}"
}
```

**Comment by mkosynskyi** [comment]
Hi @antonbabenko !
Thanks for advice.
When i added this string to my redshift module i received another error
```
module "redshift" {
  source  = "terraform-aws-modules/redshift/aws"
  version = "1.4.0"

  cluster_identifier      = "my-cluster"
  cluster_node_type       = "dc1.large"
  cluster_number_of_nodes = 1

  cluster_database_name   = "mydb"
  cluster_master_username = "mydbuser"
  cluster_master_password = "MySecretPassw0rd"

  subnets                = ["${module.vpc.redshift_subnets}"]
  vpc_security_group_ids = ["${module.sg.this_security_group_id}"]
  redshift_subnet_group_name = "${module.vpc.redshift_subnet_group}"

}
```
Error: Error running plan: 1 error(s) occurred:

* module.redshift.aws_redshift_subnet_group.this: aws_redshift_subnet_group.this: value of 'count' cannot be computed

**Comment by worldchanger** [comment]
I have the same problem as you with the subnet group.  I do have a fix for your Internet Gateway issue.

This is what I did to add the IGW to the route table.

**Add the following section to your outputs.tf** 
```
output "igw_id" {
  description = "The ID of the Internet Gateway"
  value       = "${module.vpc.igw_id}"
}
```

**Add the following section outside of your vpc module in your main.tf**
```
resource "aws_route" "internet_access" {
  route_table_id          = "${module.vpc.redshift_route_table_ids[0]}"
  destination_cidr_block  = "0.0.0.0/0"
  gateway_id              = "${module.vpc.igw_id}"
}
```

**Comment by worldchanger** [comment]
Ok so this is odd I ran it without my rds and it ran fine, did a destroy, then tried to re-deploy and it failed with the same error you saw:

`module.redshift.aws_redshift_subnet_group.this: aws_redshift_subnet_group.this: value of 'count' cannot be computed`

**Comment by ricbra** [comment]
I encounter the exact same issue when I try the workaround of @antonbabenko ... Anyone got a suggestion how to fix this?

**Comment by antonbabenko** [comment]
`value of 'count' cannot be computed` is one of the most well-known issue in Terraform 0.11 which was discussed in many places like this - https://docs.cloudposse.com/troubleshooting/terraform-value-of-count-cannot-be-computed/

I am not sure what else we can do in this module.

**Comment by bryantbiggs** [comment]
please try upgrading to the latest v3.x and let us know if this still persists - closing for now
