### ISSUE TITLE
Changing Cluster Database name

### ISSUE THREAD

**Issue by aelaa** [terraform-aws-modules/terraform-aws-redshift#11]
I'm trying to import an existed Redshift cluster and change its parameters, includes Cluster Database name. I can't provide exact configuration, but let's consider my existed cluster had database named "AAA", and I want to change it to "BBB":
```
resource "aws_redshift_cluster" "redshift" {
  cluster_identifier = "id of existed cluster"
  database_name      = "BBB"
   ...
}
```
Import was successful, but I had `database_name = "AAA"` in state.
In the plan of any following changes I have planned change of its name:
```
  ~ aws_redshift_cluster.redshift
      database_name:                       "BBB" => "AAA"
```

After applying I've got this error (caused by dependent Firehose stream creating):

```
Terraform Version: 0.11.11
    Resource ID: aws_kinesis_firehose_delivery_stream.processed
    Mismatch reason: attribute mismatch: redshift_configuration.0.cluster_jdbcurl
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"redshift_configuration.0.cluster_jdbcurl":*terraform.ResourceAttrDiff{Old:"jdbc:redshift://<private data>.us-east-1.redshift.amazonaws.com:5439/AAA", New:"jdbc:redshift://<private data>.us-east-1.redshift.amazonaws.com:5439/BBB", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

During an investigation I've found that one cannot change Cluster Database name after creating a cluster.
I haven't found any information about changing Cluster Database name in AWS documentation, neither any option in AWS console allows to do that. But Terraform trying to do it, which causes errors during applying. It seems that during plan stage it uses BBB as database name, but during apply stage redshift resource received new data from AWS, and database name in that data is still AAA.

**Comment by antonbabenko** [comment]
I recommend you to try to import one resource independently from the Kinesis, because it may bring some weird issues. Also, if the problem persists, consider raising a question on Terraform AWS provider repository.

Closing this issue, because it is not related to a module itself.
