### ISSUE TITLE
on terraform destroy: InvalidParameterValue: Logging has not been configured...

### ISSUE THREAD

**Issue by playersons** [terraform-aws-modules/terraform-aws-redshift#15]
terraform init , plan , apply is working fine with this module content:

```
module "redshift" {

source = "terraform-aws-modules/redshift/aws"
version = "1.6.0"

cluster_identifier = "${var.redshift_cluster_name}"
cluster_identifier = "staging-redshift"
cluster_node_type = "${var.redshift_cluster_node_type}"
cluster_number_of_nodes = "${var.redshift_cluster_node_count}"
cluster_database_name = "${var.redshift_cluster_database_name}"
cluster_master_username = "${var.redshift_cluster_master_username}"
cluster_master_password = "${var.redshift_cluster_master_password}"

###Group parameters
wlm_json_configuration = "[{\"query_concurrency\": 5}]"
enable_user_activity_logging = "true"
require_ssl = "false"
logging_bucket_name = "aws-tf-redshift-logging-${var.region}-${var.environment}"

###DB Subnet Group Inputs
subnets = "${var.redshift_subnets}"
vpc_security_group_ids = "${var.vpc_security_group_ids}"

###IAM Roles
cluster_iam_roles = "${var.redshift_cluster_iam_roles}"

publicly_accessible = "${var.redshift_publicly_accessible}"
allow_version_upgrade = "${var.redshift_allow_version_upgrade}"
automated_snapshot_retention_period = "${var.redshift_automated_snapshot_retention_period}"
encrypted = "${var.redshift_encrypted}"
kms_key_id = "${var.aws_kms_key_arn}"
```

But when it comes to tearing it down again, terraform is throwing this error:

```
Error: Error applying plan:

1 error(s) occurred:

* module.staging_redshift.module.redshift.aws_redshift_cluster.this: 1 error(s) occurred:

* aws_redshift_cluster.this: InvalidParameterValue: Logging has not been configured for this cluster.
	status code: 400, request id: c92ebc7a-4008-11e9-8863-41d9c62da034
```

It doesn't matter if logging is enabled or disabled on creation, same error anyway.

**Comment by protheantom** [comment]
Any workaround for this?

**Comment by playersons** [comment]
not really a workaround, I simply put this into the environment, whenver I run `destroy` om this stack:

`TF_WARN_OUTPUT_ERRORS = 1`

**Comment by protheantom** [comment]
thanks!

Have you tried to define "enable_logging" to "true" and "logging_s3_key_prefix" in addition to "logging_bucket_name" that do have defined?

My problem happens when "enable_logging" is defined to "false", the aws_redshift_cluster resource seems to be picky if "logging_s3_key_prefix" and "logging_bucket_name" are defined with "enable_logging" defined to "false"

terraform-aws-redshift module seems to be passing "logging_s3_key_prefix" and "logging_bucket_name" always

**Comment by StephanX** [comment]
For disabling logging, I found the following options work:

`  enable_user_activity_logging  = "false"
  enable_logging                = "false"
  logging_s3_key_prefix         = ""
  logging_bucket_name           = ""`

**Comment by bryantbiggs** [comment]
please try upgrading to the latest v3.x and let us know if this still persists - closing for now
