### ISSUE TITLE
Problem with using v2.0.0

### ISSUE THREAD

**Issue by sekka1** [terraform-aws-modules/terraform-aws-redshift#17]
Trying to use this per the instructions:

https://github.com/terraform-aws-modules/terraform-aws-redshift#usage

Copied it exactly.

Getting this error:

```
$ terraform init
Initializing modules...
- module.redshift
Error downloading modules: Error loading modules: module redshift: Error parsing .terraform/modules/80d141865a21b533db2c8041b5ed84d0/terraform-aws-modules-terraform-aws-redshift-272a13b/main.tf: At 3:32: Unknown token: 3:32 IDENT coalesce
```

**Comment by antonbabenko** [comment]
Looks like you are using Terraform 0.11, which means you need to use version `~> 1.0` of this module. 

See this section in README - https://github.com/terraform-aws-modules/terraform-aws-redshift#terraform-versions

PS: Remember to remove `.terraform` directory.

**Comment by sekka1** [comment]
Ah yup..  Thanks.

**Comment by sekka1** [comment]
Re ran it with the updated `terraform` version and I get this error:

```
module.redshift.aws_redshift_parameter_group.this[0]: Refreshing state... [id=my-cluster-redshift-1-0-custom-params]

Error: ClusterParameterGroupNotFound: ClusterParameterGroup my-cluster-redshift-1-0-custom-params not found.
        status code: 404, request id: db193546-92e1-11e9-877a-5ba2ea6ac489
```

Same thing.  Just trying to run the example as is with no changes.

**Comment by walkafwalka** [comment]
I am also getting a related error.
```
Error: Error in function call

  on .terraform/modules/redshift/terraform-aws-modules-terraform-aws-redshift-272a13b/main.tf line 9, in locals:
   9:   parameter_group_name = coalesce(
  10: 
  11: 
  12: 
    |----------------
    | aws_redshift_parameter_group.this is empty tuple
    | var.parameter_group_name is ""

Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```
This is after running import on an unrelated resource.

**Comment by bryantbiggs** [comment]
please try upgrading to the latest v3.x and let us know if this still persists - closing for now
