### ISSUE TITLE
Missing tags on aws_redshift_parameter_group resource

### ISSUE THREAD

**Issue by idnorton** [terraform-aws-modules/terraform-aws-redshift#21]
Tags not present when creating the aws_redshift_parameter_group resource.

**Comment by idnorton** [comment]
Fixes #20

**Comment by idnorton** [comment]
Adding an issue for the PR previously created.

**Comment by antonbabenko** [comment]
Fixed in [v2.3.0](https://github.com/terraform-aws-modules/terraform-aws-redshift/releases/v2.3.0) by PR #20
