### ISSUE TITLE
Updating the parameter value for wlm_json_configuration causes a need for rebooting redshift

### ISSUE THREAD

**Issue by darwinyip** [terraform-aws-modules/terraform-aws-redshift#25]
For some reason, updating the json content for wlm_json_configuration parameter causes Redshift to go into a state of `pending-reboot`. However doing the same change via the console does not cause the issue. I have automatic WLM setup, and the fields I am updating are considered dynamic properties.

Here is the document for reference https://docs.aws.amazon.com/redshift/latest/dg/cm-c-wlm-dynamic-properties.html

**Comment by antonbabenko** [comment]
Hi @darwinyip !

From https://docs.aws.amazon.com/redshift/latest/mgmt/workload-mgmt-config.html :
> The WLM configuration properties are either dynamic or static. You can apply dynamic properties to the database without a cluster reboot, but static properties require a cluster reboot for changes to take effect. For more information about static and dynamic properties, see WLM Dynamic and Static Configuration Properties.

There is nothing that we can do in this module or in [Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws).

Closing this issue.
