### ISSUE TITLE
Missing cluster_security_groups argument in redshift cluster resource

### ISSUE THREAD

**Issue by arijitdey** [terraform-aws-modules/terraform-aws-redshift#36]
I was unable to set the `cluster_security_groups` value using this module. Although the input argument was available in the terraform resource documentation. 

cluster_security_groups - (Optional) A list of security groups to be associated with this cluster.

It would be great if this could be added to this module.

**Comment by arijitdey** [comment]
Also, found that the `final_snapshot_identifier` is bool in the module, where it's actually a string value.

**Comment by bryantbiggs** [comment]
please try upgrading to the latest v3.x and let us know if this still persists - closing for now
