### ISSUE TITLE
Omitting final_snapshot_identifier produces an error on terraform plan

### ISSUE THREAD

**Issue by syst0m** [terraform-aws-modules/terraform-aws-redshift#39]
The `final_snapshot_identifier` parameter is supposedly optional.
However, if I don't include it when instantiating the module, I get:
```
Error: expected length of final_snapshot_identifier to be in the range (1 - 255), got

  on .terraform/modules/ume-redshift/terraform-aws-redshift-2.5.0/main.tf line 15, in resource "aws_redshift_cluster" "this":
  15: resource "aws_redshift_cluster" "this" {



Error: invalid value for final_snapshot_identifier (must only contain alphanumeric characters and hyphens)

  on .terraform/modules/ume-redshift/terraform-aws-redshift-2.5.0/main.tf line 15, in resource "aws_redshift_cluster" "this":
  15: resource "aws_redshift_cluster" "this" {
```
Setting a value for it gets rid of the error.
I've seen some PRs related to the type, possibly related?

**Comment by aaronsua-lob** [comment]
I'm also hitting this.  Seems like the default needs to be changed from "" to "0" or something similar.  The value has to be a non zero length string.  Possibly a fix to the resource itself is needed

**Comment by mattk-ce** [comment]
same here.  even when `skip_final_snapshot` is set to `true`
