### ISSUE TITLE
Add support for Concurrency Scaling and Spectrum usage limits

### ISSUE THREAD

**Issue by mazelx** [terraform-aws-modules/terraform-aws-redshift#41]
I might be missing something in the docs but it appears usage limit for Concurrency Scaling and Spectrum is not yet supported in Terraform ? 

This feature has been announced few months ago : https://aws.amazon.com/about-aws/whats-new/2020/04/announcing-cost-controls-for-amazon-redshift-spectrum-and-concurrency-scaling/

**Comment by bryantbiggs** [comment]
Please see the linked issue in the upstream AWS provider - once this is implemented we can add it here

Please do head over to the issue and add a 👍🏽 to the ticket so that it gets prioritized https://github.com/hashicorp/terraform-provider-aws/issues/20584

**Comment by bryantbiggs** [comment]
bad bot
