### ISSUE TITLE
Error: InvalidParameterValue: Cannot use a new KmsKeyId when restoring from your own snapshot.

### ISSUE THREAD

**Issue by sanjars** [terraform-aws-modules/terraform-aws-redshift#47]
@antonbabenko, 

First of all, Thank you for all the work you have been doing! 

So the issue is, I am trying to restore from the snapshot for Redshift Cluster and I have been getting the same error again/again. I have used the same KMS key that I used for my existing cluster (which I took the snapshot from) and then try to do restore. I get the error

` Error: InvalidParameterValue: Cannot use a new KmsKeyId when restoring from your own snapshot.` ,

 then I tried to create a new KMS key and then restored it but still the same error. I am not sure, but I thought I need to use the same KMS key with which I created my original cluster (in my opinion). Do you have any suggestions on what I might be missing? 

Thanks again!

**Comment by BastianM3** [comment]
FYI - I ran into this same issue. The trick is to set `encrypted` to true and leave the `kms_key_id` field `null`:

```
[...]
  encrypted              = var.dw_redshift_enable_kms_encryption
  kms_key_id             = var.dw_redshift_enable_kms_encryption && var.dw_redshift_use_snapshot == false ? aws_kms_key.data_kms.arn  : null
[...]
```

Redshift automatically uses the KMS key id associated with the encrypted snapshot 👍🏻
