### ISSUE TITLE
Cluster relocation

### ISSUE THREAD

**Issue by ogutierrez0917** [terraform-aws-modules/terraform-aws-redshift#59]
Can you add Cluster relocation?

**Comment by sarahmk125** [comment]
Bumping this! Cluster relocation would be incredibly useful given yesterday's AWS outage on only us-east-1c. Enabling cluster relocation in the console is good, but storing the enabled cluster relocation in Terraform state so it can't accidentally be disabled would be great.

**Comment by bryantbiggs** [comment]
we cannot support until the provider supports the functionality:
- upstream issue https://github.com/hashicorp/terraform-provider-aws/issues/19098
- upstream potential PR https://github.com/hashicorp/terraform-provider-aws/pull/20812

**Comment by bryantbiggs** [comment]
Note - please go to the linked issue and give your 👍🏽 and raise awareness to help get that change across the line
