### ISSUE TITLE
Allow settings the default role

### ISSUE THREAD

**Issue by rgarrigue** [terraform-aws-modules/terraform-aws-redshift#67]
## Is your request related to a new offering from AWS?

4.16.0 added argument default_iam_role_arn to aws_redshift_cluster

## Is your request related to a problem? Please describe.

Creating my redshifdt cluster, I need to associate a default role allowing the COPY (from S3 bucket to redshift table) command. I can associate the said role but not set it as default. 

## Describe the solution you'd like.

Add `default_iam_role_arn` var

## Describe alternatives you've considered.

Clicking in the UI for now

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
