### ISSUE TITLE
Invalid value for master_password (cannot contain [/@"' ])

### ISSUE THREAD

**Issue by leondkr** [terraform-aws-modules/terraform-aws-redshift#71]
## Description

When creating a new **Redshift cluster**, I am facing the following error when using the attribute `create_random_password = true`

```
│ Error: invalid value for master_password (cannot contain [/@"' ])
│ 
│   with module.redshift_dwh.aws_redshift_cluster.this[0],
│   on .terraform/modules/redshift_dwh/main.tf line 62, in resource "aws_redshift_cluster" "this":
│   62:   master_password                  = var.snapshot_identifier != null ? null : local.master_password
│ 
╵
```

## Versions

- Module version [Required]: `4.0.2`

- Terraform version: `v1.2.6`

- Provider version(s): `registry.terraform.io/hashicorp/aws v4.33.0`

## Reproduction Code [Required]

```
module "redshift" {
  source  = "terraform-aws-modules/redshift/aws"
  version = "4.0.2"

  node_type = "dc2.large"

  master_username        = "redshift"
  create_random_password = true
```

## Expected behavior

The attribute `create_random_password = true` helps creating the password automatically.

## Actual behavior

The randomized password has special characters that Redshift does not allow for creation.

## Additional context

For workaround, I have done as follows
- added a custom `random_password` resource to remove special characters.
- set `create_random_password = false`
- manually set `master_password` with reference to my custom `random_password` resource

**Comment by bryantbiggs** [comment]
closed in #72
