### ISSUE TITLE
Expose random master password.

### ISSUE THREAD

**Issue by adam-bentley** [terraform-aws-modules/terraform-aws-redshift#75]
## Describe the solution you'd like.
I'd like to be able to use the random master password generated by the module in my terraform script. This is so I can store it in places like secrets manager or use it in lambda function environment variables.

## Describe alternatives you've considered.
The alternative is to not use the randomly generated password and set and control it via the terraform script. 

## Additional context
I see this as not an essential improvement but it would be a nice helper feature.

**Comment by leondkr** [comment]
Yes, you can do it without having random master password to be enabled.

Firstly, set the attribute into `false`.
```
  create_random_password = false
```

Secondly, create the `random_password` resource.

```
resource "random_password" "my_password" {}
```

Thirdly, assign the `master_password` attribute with your own created resource.

```
  master_password = random_password. my_password[0].result
```

Lastly, make it with Secrets Manager or Parameter Store which is up to your decisions.

**Comment by adam-bentley** [comment]
Yeah, I understand that. I was saying it would be nice to expose the password so that you can use the module to generate a password and use that feature instead of manually doing it. It makes the module more flexible and reduces accompanying code.

**Comment by leondkr** [comment]
From what I observe, the random password is served just for creation purpose only. For best practice, we have to update/change it immediately so people does not think about your exposing from the start.

Also, your request is nice that we then can manage it over Secrets Manager or related. Then, it leads to the story of secret rotation using Lambda functions which takes effort so they have not yet provided this feature.
