### ISSUE TITLE
Deprecated attribute cluster_security_groups

### ISSUE THREAD

**Issue by traxverlis** [terraform-aws-modules/terraform-aws-redshift#76]
## Description

╷
│ Warning: Deprecated attribute
│
│   on .terraform\modules\redshift.redshift\outputs.tf line 71, in output "cluster_security_groups":
│   71:   value       = try(aws_redshift_cluster.this[0].cluster_security_groups, [])
│
│ The attribute "cluster_security_groups" is deprecated. Refer to the provider documentation for details.
│
│ (and one more similar warning elsewhere)

- [*] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
last

- Terraform version:
Terraform v1.2.7

- Provider version(s):
provider registry.terraform.io/hashicorp/aws v4.45.0
provider registry.terraform.io/hashicorp/random v3.4.3
provider registry.terraform.io/hashicorp/tls v4.0.4

### Terminal Output Screenshot(s)

![Capture d’écran 2022-12-08 100833](https://user-images.githubusercontent.com/5329924/206405276-68f5b34e-d285-4f97-a82d-1664dc22de0d.png)

**Comment by davidhuser** [comment]
getting the same, on v.4.54.0 it does not seem to be marked deprecated in the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#cluster_security_groups)

did you just disregard the warning @traxverlis ?
