### ISSUE TITLE
Adding cluster_revision_number to the variable list

### ISSUE THREAD

**Issue by krkarizs** [terraform-aws-modules/terraform-aws-redshift#77]
## Is your request related to a new offering from AWS?
It is not related to a new offering.

## Is your request related to a problem? Please describe.

After creating the Redshift cluster terraform adds cluster_revision_number to the state. This revision number changes when AWS updates the cluster version, but Terraform tries to change it back to the old revision number used before the update even though the allow_version_upgrade property is set to true.

## Describe the solution you'd like.

Adding a cluster_revision_number variable to make it possible to rewrite the old revision numbers.

## Additional context

Revision number 44126 was introduced in November while 44903 in December. The came with the same AWS patch that might be the reason why the allow_version_upgrade doesn't work.

####Plan output
`  # module.redshift_segment.aws_redshift_cluster.this[0] has changed
  ~ resource "aws_redshift_cluster" "this" {
      ~ cluster_revision_number              = "44126" -> "44903"
        id                                   = "xxxxxx"
        tags                                 = {}`

**Comment by antonbabenko** [comment]
Great proposal! Please open a PR!
