### ISSUE TITLE
Deprecation warnings with latest AWS provider versions

### ISSUE THREAD

**Issue by marlovil** [terraform-aws-modules/terraform-aws-redshift#82]
## Description

We are getting deprecation warnings with latest AWS provider version.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 4.0.3
- Terraform version: 1.3.5
- Provider versions: 4.53.0 and 4.62.0

Run a `terraform plan` or `terraform apply`

## Expected behavior

Don't get deprecation warnings

## Actual behavior

We are getting deprecation warnings with latest AWS provider version. The same as #81 

### Terminal Output Screenshot(s)

```
│ Warning: Deprecated attribute
│ 
│   on .terraform/modules/redshift/outputs.tf line 71, in output "cluster_security_groups":
│   71:   value       = try(aws_redshift_cluster.this[0].cluster_security_groups, [])
│ 
│ The attribute "cluster_security_groups" is deprecated. Refer to the
│ provider documentation for details.

```

**Comment by bryantbiggs** [comment]
we do not control these warnings, the provider does. This will most likely be resolved after v5 of the AWS provider is released https://github.com/hashicorp/terraform-provider-aws/issues/29842 and this project is updated to use v5 at which time the deprecated arguments will have been removed

**Comment by marlovil** [comment]
Thanks @bryantbiggs! 

I've found a related issue about his: https://github.com/hashicorp/terraform-provider-aws/issues/29480

Closing this issue.
