### ISSUE TITLE
Deprecation Error - Unsupported attribute "cluster_security_groups"

### ISSUE THREAD

**Issue by matt-dancer-adwanted** [terraform-aws-modules/terraform-aws-redshift#85]
## Description

As EC2-Classic features have now been removed, when using the latest Terraform AWS Provider (v5.0.0 or later), the following error is reported when running a 'terraform validate:'

> Error: Unsupported attribute
> 
>   on .terraform/modules/redshift_standalone/outputs.tf line 71, in output "cluster_security_groups":
>   71:   value       = try(aws_redshift_cluster.this[0].cluster_security_groups, [])
> 
> This object has no argument, nested block, or exported attribute named "cluster_security_groups".

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

Issues [#81](https://github.com/terraform-aws-modules/terraform-aws-redshift/issues/81) and [#82](https://github.com/terraform-aws-modules/terraform-aws-redshift/issues/82) report these as deprecation warnings only (i.e. not show-stopping), but these now appear as full-blown errors. 

## Versions

- Module version: 4.0.3

- Terraform version: 1.4.6
- Provider version(s): 5.0.1

Run a `terraform validate`, `terraform plan` and/or `terraform apply`.

## Expected behavior

Successful execution without errors. 

## Actual behavior

Execute fails with `Error: Unsupported attribute`

### Terminal Output Screenshot(s)

> Error: Unsupported attribute
> 
>   on .terraform/modules/redshift_standalone/outputs.tf line 71, in output "cluster_security_groups":
>   71:   value       = try(aws_redshift_cluster.this[0].cluster_security_groups, [])
> 
> This object has no argument, nested block, or exported attribute named "cluster_security_groups".

**Comment by dbdoyle182** [comment]
This is preventing any deployments of this module regardless of terraform version, aws version or module version.

**Comment by bryantbiggs** [comment]
pinning your local AWS provider version to `< 5.0` should alleviate the issue until the module is updated to support v5.0

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.0.0 :tada:
