### ISSUE TITLE
Error: creating Redshift Cluster IAM Roles

### ISSUE THREAD

**Issue by GISTech01** [terraform-aws-modules/terraform-aws-redshift#88]
## Description

When trying to deploy a redshift cluster with "iam_role_arns" it fails as its trying to associate iam roles to the redshift cluster that is still being deployed and its in a modifying state.

## Versions

- Module version: 
   - 5.0.0

- Terraform version:

    - Terraform 1.4.6
- Provider version(s):

    - AWS Provider 5.12.0
    - Random Provider 3.2.0
    - Docker 3.0.0

## Reproduction Code 

```hcl
module ktts-redshift {
    source  = "terraform-aws-modules/redshift/aws"
    version = "~> 5.0.0"

    cluster_identifier = var.cluster_identifier
    allow_version_upgrade = var.allow_version_upgrade
    node_type = var.redshift_node_type
    number_of_nodes = var.redshift_number_of_nodes
    database_name = var.redshift_database_name
    create_random_password = var.create_random_password

    master_username = jsondecode(data.aws_secretsmanager_secret_version.redshift_secret.secret_string)["Username"]
    master_password  = jsondecode(data.aws_secretsmanager_secret_version.redshift_secret.secret_string)["Password"]

    enhanced_vpc_routing = var.enhanced_vpc_routing
    iam_role_arns = var.redshift_iam_role_arns
    vpc_security_group_ids = [module.ktts-redshift-sg.security_group_id]
    subnet_ids = module.vpc.redshift_subnets
    availability_zone_relocation_enabled = var.enable_az_relocation

    logging = {
        enable = var.enable_redshift_logging
        bucket_name = module.s3-bucket-redshift.s3_bucket_id
        s3_key_prefix = "${var.redshift_database_name}/"
    }
    create_subnet_group = var.create_subnet_group
    subnet_group_name  = module.vpc.redshift_subnet_group
}
```

Run Terraform apply against Terraform Redshift module with associated iam roles

## Expected behavior

The Redshift cluster should be deployed prior to the iam roles trying to be attached.

## Actual behavior

The IAM roles are trying to be attached while the redshift cluster is in modifying state

**Comment by bryantbiggs** [comment]
you have not provided a proper reproduction that can be deployed - how would we begin to triage or troubleshoot?

**Comment by Latyn4ik** [comment]
I have similar problem with creating of aws_redshift_cluster_iam_roles.
This problem appeared after changing:
**node_type**: from _"dc2.large"_  to _"ra3.xlplus"_
**number_of_nodes**: from _1_ to _2_

**Versions:**
Provider version(s): hashicorp/aws v5.34.0
Terraform version: 1.5.5
Module version: 5.1.1

**ERROR MESSAGE:**
`│ Error: creating Redshift Cluster IAM Roles (dev-platform-redshift-main-0): InvalidClusterState: The Cluster is being modified by a concurrent operation. Please check the Cluster's status and try again.
│       status code: 400, request id: 93d7b793-de27-414b-b80a-06541e0fd8a7
│ 
│   with module.redshift.aws_redshift_cluster_iam_roles.this[0],
│   on .terraform/modules/redshift/main.tf line 106, in resource "aws_redshift_cluster_iam_roles" "this":
│  106: resource "aws_redshift_cluster_iam_roles" "this" {`

**Comment by bryantbiggs** [comment]
the error message is quite clear there 
> The Cluster is being modified by a concurrent operation. Please check the Cluster's status and try again.

You can't make changes while the cluster is updating. Looks like this might be an issue for the upstream provider where the provider needs to wait for the cluster to finish updating before allowing other calls to proceed

**Comment by Latyn4ik** [comment]
I have similar problem with creating of aws_redshift_cluster_iam_roles.
This problem appeared after changing:
**node_type**: from _"dc2.large"_  to _"ra3.xlplus"_
**number_of_nodes**: from _1_ to _2_

**Versions:**
Provider version(s): hashicorp/aws v5.34.0
Terraform version: 1.5.5
Module version: 5.1.1

**ERROR MESSAGE:**
`│ Error: creating Redshift Cluster IAM Roles (dev-platform-redshift-main-0): InvalidClusterState: The Cluster is being modified by a concurrent operation. Please check the Cluster's status and try again.
│       status code: 400, request id: 93d7b793-de27-414b-b80a-06541e0fd8a7
│ 
│   with module.redshift.aws_redshift_cluster_iam_roles.this[0],
│   on .terraform/modules/redshift/main.tf line 106, in resource "aws_redshift_cluster_iam_roles" "this":
│  106: resource "aws_redshift_cluster_iam_roles" "this" {`

**Comment by Latyn4ik** [comment]
> the error message is quite clear there
> 
> > The Cluster is being modified by a concurrent operation. Please check the Cluster's status and try again.
> 
> You can't make changes while the cluster is updating. Looks like this might be an issue for the upstream provider where the provider needs to wait for the cluster to finish updating before allowing other calls to proceed

yes, you are right, I also have a null_resource that changes the password, i.e. the cluster deployment is over, the password variable works immediately. Thanks
```
# This resource needs to change password for cluster in case if cluster deployed based on snapshot
# Because after deploy from snapshot old password still unchanged
# resource "null_resource" "change_password" {
#   count = var.snapshot_identifier != null ? 1 : 0

#   provisioner "local-exec" {
#     command = "aws redshift modify-cluster --cluster-identifier ${module.redshift.cluster_identifier} --master-user-password '${random_password.redshift_password.result}'"
#   }

#   depends_on = [null_resource.check_cluster_status]
# }
```
