### ISSUE TITLE
Missing `manage_master_password` causes Null condition error

### ISSUE THREAD

**Issue by far-rel** [terraform-aws-modules/terraform-aws-redshift#89]
## Description

After updating the module version from 5.0.0 to 5.1.0 we encountered an error when trying to apply our previously working configuration (screenshot below). After checking the new release we resolved that explicitly setting `manage_master_password` to false solves the issue. According to the documentation 
> One of master_password or manage_master_password is required unless snapshot_identifier is provided.

and we do provide `master_password` (see example), so we did not expect to have an issue with newer version of the module.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 5.1.0

- Terraform version:  v1.6.4
- Provider version(s):
  - provider registry.terraform.io/hashicorp/aws v5.31.0 
  - provider registry.terraform.io/hashicorp/random v3.6.0

## Reproduction Code [Required]

```terraform
module "redshift" {
  source  = "terraform-aws-modules/redshift/aws"
  version = "5.1.0"

  cluster_identifier     = "test"
  master_username        = "admin"
  master_password        = "password"
  create_random_password = false
}
```

Run `terraform plan`

## Expected behavior

`manage_master_password` variable is optional when `master_password` is provided

## Actual behavior

Missing `manage_master_password` variable causes a `Null condition` error

### Terminal Output Screenshot(s)

![Zrzut ekranu 2024-01-15 o 09 48 39](https://github.com/terraform-aws-modules/terraform-aws-redshift/assets/1194078/a8c02788-6f9a-428c-b60a-c45e882c20fd)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.1.1 :tada:

**Comment by jay-barker-deltatre** [comment]
Hello,

We are affected by this issue but the terraform registry is not showing 5.1.1, the latest is showing as 5.1.0

**Comment by antonbabenko** [comment]
@jay-barker-deltatre FIxed with the stick :)

**Comment by jay-barker-deltatre** [comment]
Thanks for the super fast response! Its showing now
