### ISSUE TITLE
Enable Redshift logging to CloudWatch

### ISSUE THREAD

**Issue by aridgewell-firemind** [terraform-aws-modules/terraform-aws-redshift#91]
Can we please enable the ability to enable audit logging to CloudWatch? Currently the only option seems to be to S3.

  logging = {
    enable        = true
    bucket_name   = module.s3_logs.s3_bucket_id
    s3_key_prefix = local.s3_prefix
  }

If i do not set the bucket_name then the plan fails.

This is available in the AWS provider https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#logging.

Could this functionality please be added to enable us to align our reshift logging with our other aws services?

**Comment by magreenbaum** [comment]
Here is an [example](https://github.com/terraform-aws-modules/terraform-aws-redshift/blob/1154bdba6d3215fcf9830c43363be09e2b2ce51d/examples/complete/main.tf#L220-L224) on enabling audit logging to cloudwatch.

**Comment by aridgewell-firemind** [comment]
Many thanks for your help with this one. I have now tested that these changes work as expected.
